config/routes.rb
BookWriter::Application.routes.draw do

  resources :booksearches

  get "conversations/index"

  mount Ckeditor::Engine => '/ckeditor'

  root :to => 'books#index'

  devise_for :users, :controllers => {:registrations => "registrations"} # route to custom controller for recaptcha verification

  resources :books do
    get 'print', :on => :member
    post 'close', :on => :member
    get 'new_edition', :on => :member
    resources :chunks, :except => [:index]
  end

  get 'show_simple_searchform' => 'books#show_simple_searchform' # for javascript
  get 'show_advanced_searchform' => 'books#show_advanced_searchform' # for javascript

  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
    end
  end
  get 'chunk_version/:book_id/:id' => 'chunks#version', :as => :chunk_version

  get 'conversations/:id' => "conversations#show", :as => :mailboxer_conversation, :constraints => {:id => /\d+/ } # generates  mailboxer_conversation_path
  post '/conversations/:id/reply' => "conversations#reply", :as => :reply_mailboxer_conversation # generates  reply_mailboxer_conversation_path

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_filter :authenticate_user!
  after_filter :read_conversation, :only => [:show] # mark all conversation-Messages as Read
  helper :conversations
  helper_method :mailbox, :conversation

  # /conversations
  def index
    @mailbox = mailbox # Mailbox initialisieren
  end

  # /conversations/new
  def new
    # not needed, because Mailboxer creates a conversation automatically by first "send_message"-method invoke
  end

  # /conversations/create
  def create
    recipient_names = conversation_params(:recipients).split(',')
    recipients = User.where(username: recipient_names).all

    conversation = current_user.send_message(recipients, *conversation_params(:body, :subject)).conversation
    redirect_to conversation
  end

  # /conversations/:id
  def show
    @conversation ||= conversation
    respond_to do |format|
      format.html { render_check_template }
      format.json { render json: @conversation }
    end
  end

  #  /conversations/:id/reply
  def reply
    @conversation = conversation
    current_user.reply_to_conversation(@conversation, *message_params(:body, :subject))
    flash[:notice] = "Message has been sent!"
    redirect_to @conversation
  end

  # /conversations/:id/trash
  def trash
    conversation.move_to_trash(current_user)
    redirect_to :conversations
  end

  private
  def mailbox
    @mailbox ||= current_user.mailbox
  end

  def conversation
    @conversation ||= mailbox.conversations.find(params[:id])
  end

  def read_conversation
    conversation.mark_as_read(current_user)
  end

  def conversation_params(*keys)
    fetch_params(:conversation, *keys)
  end

  def message_params(*keys)
    fetch_params(:message, *keys)
  end

  def fetch_params(key, *subkeys)
    params[key].instance_eval do
      case subkeys.size
        when 0 then self
        when 1 then self[subkeys.first]
        else subkeys.map{|k| self[k] }
      end
    end
  end

end

app/helpers/conversations_helper.rb
module ConversationsHelper
  # Generally: Overloading is not allowed in ruby

  def number_of_all_unreadMessages
    conversations = current_user.mailbox.inbox
    conversations.each do |c|
      number += numberOfunreadMessages(c)
    end
    return number
  end

  def number_of_unreadMessages(conversationInstance)
    number = 0
    conversationInstance.receipts_for(current_user).each do |receipt|
      if !receipt.is_read?
        number += 1
      end
    end
    return number
  end

end

app/views/conversations/_conversation.html.erb
<%= content_tag_for(:li, conversation) do |conversation| %>
    <p>
      <table>
          <tr>
            <td><%= link_to conversation.subject, conversation %></td>
            <td>(<%= render :partial => "participant", :collection => conversation.participants %>)</td>
            <td><% numberOfUnreadMessages = number_of_unreadMessages(conversation) %>
                <% if(numberOfUnreadMessages > 1) %> <!-- HelperMethod defined in helpers/conversations_helper -->
                   (<%= numberOfUnreadMessages %> Messages unread)
                <% elsif (numberOfUnreadMessages == 1) %>
                    (<%= numberOfUnreadMessages %> Message unread)
                <% end %>
            </td>
            <td><%= link_to I18n.t('views.destroy'), trash_conversation_path(conversation), method: :post, data: {confirm: I18n.t('views.are_you_sure')} %></td>
          </tr>
      </table>
    </p>
<% end %>

app/views/conversations/_form.html.erb
<%= simple_form_for :conversation, url: :conversations do |f| %>
    <p>
      <%= f.label "Recipient" %><br/>
      <%= f.text_field :recipients %>
    </p>
    <p>
      <%= f.label "Subject" %><br/>
      <%= f.text_field :subject %>
    </p>
    <p>
      <%= f.label "Message" %><br/>
      <%= f.text_area :body %>
    </p>
    <div class="form-actions">
      <%= f.button :submit, 'Send Message', class: 'btn-primary' %>
      <%= submit_tag 'Cancel', type: :reset, class: 'btn btn-danger' %>
    </div>
<% end %>

app/views/conversations/_participant.html.erb
<%= participant.username %>;

app/views/conversations/index.html.erb
<h1>Conversations</h1>
<h2>Inbox</h2>
<ul>
  <%= render(:partial => "conversation", :collection => mailbox.inbox) || 'You didn\'t receive any messages' %>
</ul>
<%= link_to 'Start Conversation', :new_conversation %>

app/views/conversations/new.html.erb
<h1>Start Conversation</h1>
<%= render 'form' %>

app/views/conversations/show.html.erb
<h1>
  <%= @conversation.subject %>
</h1>
<ul>
  <%= content_tag_for(:li, @conversation.receipts_for(current_user)) do |receipt| %>
      <% message = receipt.message %>
      <h3>
        <%= "Subject: #{message.subject}" %>
        <% if !receipt.is_read? %>
            NEW!
        <% end %>
      </h3>
      <h4>
        <%= "From: #{message.sender.username} Time: #{receipt.created_at.strftime("%a, %m/%e/%Y %I:%M %p")}" %>
      </h4>
      <p>
        <%= message.body %>
      </p>
  <% end %>
</ul>
<%= render 'messages/form', conversation: @conversation %>
<%= button_to I18n.t('views.back'), :back, method: :get %>