config/routes.rb
BookWriter::Application.routes.draw do

  resources :booksearches

  get "conversations/index"

  mount Ckeditor::Engine => '/ckeditor'

  root :to => 'books#index'

  devise_for :users, :controllers => {:registrations => "registrations"} # route to custom controller for recaptcha verification

  resources :books do
    get 'print', :on => :member
    post 'close', :on => :member
    get 'new_edition', :on => :member
    resources :chunks, :except => [:index]
  end

  get 'show_simple_searchform' => 'books#show_simple_searchform' # for javascript
  get 'show_advanced_searchform' => 'books#show_advanced_searchform' # for javascript

  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
    end
  end
  get 'chunk_version/:book_id/:id' => 'chunks#version', :as => :chunk_version

  get 'conversations/:id' => "conversations#show", :as => :mailboxer_conversation, :constraints => {:id => /\d+/ } # generates  mailboxer_conversation_path
  post '/conversations/:id/reply' => "conversations#reply", :as => :reply_mailboxer_conversation # generates  reply_mailboxer_conversation_path

end

app/models/book.rb
class Book < ActiveRecord::Base #SQL Code nur in ActiveBookRecord Trennung von Technik (SQL) und
# ActiveRecord::Base ist die Oberklasse aller Model- Klassen


  attr_accessible :title, :edition, :published, :genre, :abstract, :tags, :user_ids, :closed
 #attr_accessible specifies a white list of model attributes that can be set via mass-assignment


  has_and_belongs_to_many :users # generiert Tabelle books_users
  has_many :chunks

  validates_presence_of :title, :edition

  # custom error message for the author checkboxes displays the translation defined in C:\RubyOnRailsProject\BookWriter\config\locales\*.yml
  validates_presence_of :users, :message => I18n.translate('errors.messages.must_be_selected')


  validates :edition, :uniqueness => {:scope => :title}
  before_destroy :destroy_chunks

  def sliced_attributes
    attributes.slice('title', 'genre', 'abstract', 'tags') #Whitelisting
  end

  def published?
    !published.nil?
  end

  def is_author?(author)
    self.users.map(&:id).include?(author.id)
  end

  def has_chunks?
    !chunks.empty?
  end

  def max_chunk_position
    has_chunks? ? chunks.max_by(&:position).position : 0
  end

  def users_list
    users.collect { |u| u.username }.join(',')
  end

  def users_list_real_names
    users.collect { |u| u.first_name + ' ' + u.last_name }.join(',')
  end

  private
  def destroy_chunks
    chunks.each do |chunk|
      chunk.destroy
    end
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController # Fachlogik SQL freie Zone

  layout 'books_and_chunks'
  before_filter :authenticate_user! # bevor eine action im controller aufgerufen werden kann muss man mit devise sich authentifizieren
  before_filter :find_all_users, :only => [:new, :edit, :new_edition] #for the methods :new, :edit, :new_edition @users = User.all insert DRY / Metaprogramming
  helper_method :sort_column, :sort_direction, :search_is_for_published



  # GET /books
  # GET /books.json
  def index # als root Seite gewählt kann nur angewählt werden, wenn man mit devise eingeloggt ist
    @booksearch = booksearch
    @books = @booksearch.search.order(sort_column + " " + sort_direction).paginate(:per_page => 3, :page => params[:page]); #searchresults.order(sort_column + " " + sort_direction).paginate(:per_page => 3, :page => params[:page]);

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @books }
      format.js #index.js.erb
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @book = Book.find_by_id(params[:id].to_i) # wenn bei Paraams id

    respond_to do |format|
      format.html { render_check_template }
      format.json { render json: @book }
    end
  end

  def print
    @book = Book.find_by_id(params[:id].to_i)

    respond_to do |format|
      format.pdf do
        render :pdf => @book.title, :layout => 'print'
      end
    end

  end

  # GET /books/new
  # GET /books/new.json
  def new
    @book = Book.new

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/1/edit
  def edit
    @book = Book.find_by_id(params[:id].to_i)

    unless @book.closed?
      render_check_template
    else
      flash[:error] = I18n.t('views.book.flash_errors.book_is_closed') # gibt ein flash Fenster mit der fehlermeldung aus
      render_check_template 'show'
    end
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(params[:book])

    old_book_id = session[:old_book_id]

    respond_to do |format|
      if @book.save
        unless old_book_id.nil?
          old_book = Book.find(old_book_id)
          old_book.chunks.each do |old_chunk|
            chunk = Chunk.new(old_chunk.sliced_attributes)
            chunk.book = @book
            chunk.save
            @book.chunks << chunk
          end
          session[:old_book_id] = nil
        end
        format.html { redirect_to @book, notice: I18n.t('views.book.flash_messages.book_was_successfully_created') }
        format.json { render json: @book, status: :created, location: @book }
      else
        format.html do
          @users ||= User.all
          render action: 'new'
        end
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /books/1
  # PUT /books/1.json
  def update
    @book = Book.find_by_id(params[:id].to_i)

    if params[:update_chunk_order_only] == 'true'
      chunk_ids = params[:chunk_order].split(',')
      chunk_ids.each_with_index do |chunk_id, i|
        chunk = Chunk.find(chunk_id)
        chunk.update_attribute(:position, i)
      end
    else
      params[:book][:user_ids] ||= []
    end

    respond_to do |format|
      if params[:update_chunk_order_only] == 'true'
        format.html { render 'show', layout: false }
      else
        if @book.update_attributes(params[:book])
          format.html { redirect_to @book, notice: I18n.t('views.book.flash_messages.book_was_successfully_updated') }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @book.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  def close
    @book = Book.find(params[:id])

    respond_to do |format|
      if @book.update_attributes(:closed => true, :published => Time.now)
        format.html { redirect_to @book, notice: I18n.t('views.book.flash_messages.book_was_successfully_closed') }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def new_edition
    old_book = Book.find_by_id(params[:id])
    @book = Book.new(old_book.sliced_attributes)
    @book.users = old_book.users

    session[:old_book_id] = old_book.id
    render 'new'
  end

# DELETE /books/1
# DELETE /books/1.json
  def destroy
    @book = Book.find_by_id(params[:id].to_i)
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :no_content }
    end
  end


  def show_simple_searchform
    @booksearch = booksearch
    respond_to do |format| #
      format.js # show_simple_searchform.js.erb
    end
  end

  def show_advanced_searchform
    @booksearch = booksearch
    respond_to do |format| #
      format.js # show_advanced_searchform.js.erb
    end
  end

  def is_published_click
    respond_to do |format| #
      format.js # is_published_click.js.erb
    end
  end

  private
  def find_all_users
    @users = User.all
  end

  def sort_column
    Book.column_names.include?(params[:sort]) ? params[:sort] : "title" # has params[:sort] included one of the column names?
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc" # has params[:direction] included one of "asc" or "dsc"
  end

  # Methods for Search
  def booksearch
    params[:booksearch]== nil ? Booksearch.new(:is_advanced => '0', :is_public => '0', :user_id => current_user.id) : Booksearch.new(params[:booksearch])
  end

  def search_is_public
    booksearch.is_public == '1'
  end

  def search_is_advanced
    booksearch.is_advanced == '1'
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_books.html.erb
<table class="pretty">
  <tr>
    <th><%= sortable "title", Book.human_attribute_name(:title) %></th>
    <th><%= sortable "edition", Book.human_attribute_name(:edition) %></th>
    <th><%= sortable "published", Book.human_attribute_name(:published) %></th>
    <th><%= sortable "genre", Book.human_attribute_name(:genre) %></th>
    <th><%= Book.human_attribute_name(:tags) %></th>
    <th><%= Book.human_attribute_name(:users) %></th>
  </tr>

  <% @books.each do |book| %>
      <tr>
        <td><%= book.is_author?(current_user) ? link_to(book.title, book) : book.title %></td>
        <td><%= book.edition %></td>
        <td><%= book.published %></td>
        <td><%= book.genre %></td>
        <td><%= book.tags %></td>
        <td><%= book.users_list %></td>
      </tr>
  <% end %>
</table>
<%= will_paginate @books %>
<script>$('.pagination a').attr('data-remote', 'true');</script>

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
    <% if @book.errors.any? %>
        <div id="error_explanation">
          <h2><%= t 'activerecord.errors.template.header', :model => Book.model_name.human, :count => @book.errors.count %></h2>

          <ul>
            <% @book.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :title %>
      <br/>
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :edition %>
      <br/>
      <%= f.text_field :edition %>
    </div>
    <div class="field">
      <%= f.label :genre %>
      <br/>
      <%= f.text_field :genre %>
    </div>
    <div class="field">
      <%= f.label :abstract %>
      <br/>
      <%= f.cktext_area :abstract %>
    </div>
    <div class="field">
      <%= f.label :tags %>
      <br/>
      <%= f.text_field :tags %>
    </div>
    <div class="field">
      <%= f.label :users %>
      <br/>
      <% @users.each do |user| %>
          <div>
            <%= check_box_tag "book[user_ids][]", user.id, @book.users.include?(user) %>
            <%= user.email %>
          </div>
      <% end %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/books/edit.html.erb
<h1><%= t 'views.book.edit.title' %></h1>

<%= render 'form' %>

<%= button_to I18n.t('views.back'), @book, method: :get %>

app/views/books/index.html.erb
<h1><%= t 'views.book.index.title' %></h1>
<!-- simple or extended search  -->
<%= link_to 'Simple Search', show_simple_searchform_path, :remote=> true, :id=> "simplesearch", :style=>'font-weight: bold;' %>
<%= link_to 'Advanced Search', show_advanced_searchform_path, :remote=> true, :id=>"advancedsearch" %>
<br>
<div id="searchform">
  <%= render 'booksearches/form_simple' unless @booksearch.is_advanced? %>
  <%= render 'booksearches/form_extended' if @booksearch.is_advanced? %>
</div>

<!--renders partial _books.html.erb-->
<div id="books"><%= render 'books' %></div>

<br/>

<%= button_to I18n.t('views.book.index.new'), new_book_path, method: :get %>

app/views/books/index.js.erb
// javascript response for Books#index action
$("#books").html("<%= escape_javascript(render ('books')) %>")

app/views/books/new.html.erb
<h1><%= t 'views.book.new.title' %></h1>

<%= render 'form' %>

<%= button_to I18n.t('views.back'), books_path, method: :get %>

app/views/books/print.pdf.erb
<div class="cover">
  <p class="title"><%= @book.title %></p>

  <p class="authors"><%= @book.users_list_real_names %></p>

  <br/><br/>

  <p><%= "#{@book.edition}. #{Book.human_attribute_name(:edition)}" %></p>

  <% if @book.published? %>
      <p><%= "#{I18n.t('views.book.export.published_on')} #{@book.published.to_s}" %></p>
  <% end %>
</div>

<div class="chapter">
  <h1><%= Book.human_attribute_name(:abstract) %></h1>

  <p><%= raw @book.abstract %></p>
</div>

<% if @book.has_chunks? %>
    <% @book.chunks.each do |chunk| %>
        <div class="chapter">
          <h1><%= chunk.title %></h1>
          <%= raw chunk.content %>
        </div>
    <% end %>
<% end %>

app/views/books/show.html.erb
<h1><%= @book.title %></h1>

<p>
  <b><%= Book.human_attribute_name(:edition) %>:</b>
  <%= @book.edition %>
</p>

<% if @book.published? %>
    <p>
      <b><%= Book.human_attribute_name(:published) %>:</b>
      <%= @book.published %>
    </p>
<% end %>

<p>
  <b><%= Book.human_attribute_name(:genre) %>:</b>
  <%= @book.genre %>
</p>

<p>
  <b><%= Book.human_attribute_name(:tags) %>:</b>
  <%= @book.tags %>
</p>

<p>
  <b><%= Book.human_attribute_name(:users) %>:</b>
  <%= @book.users_list %>
</p>

<div class="horizontal">
  <% unless @book.closed? %>
      <%= button_to I18n.t('views.edit'), edit_book_path(@book), method: :get %>
      <%= button_to I18n.t('views.book.close.close_book'), close_book_path(@book), data: {confirm: I18n.t('views.book.close.sure')} %>
  <% end %>
  <%= button_to I18n.t('views.book.new_edition'), new_edition_book_path(@book), method: :get %>
  <%= button_to I18n.t('views.book.export.pdf'), print_book_path(@book, :format => 'pdf'), method: :get %>
  <%= button_to I18n.t('views.destroy'), @book, method: :delete, data: {confirm: I18n.t('views.are_you_sure')} %>
</div>

<br/><br/><br/>

<h2><%= t 'views.chunk.index.title' %></h2>
<% if @book.has_chunks? %>
    <table>
      <tr>
        <th><%= Chunk.human_attribute_name(:title) %></th>
        <th><%= Chunk.human_attribute_name(:section) %></th>
        <th><%= Chunk.human_attribute_name(:user) %></th>
        <th><%= Chunk.human_attribute_name(:version) %></th>
        <% unless @book.closed? %>
            <th></th>
        <% end %>
      </tr>
      <% @book.chunks.each do |chunk| %>
          <tr>
            <td><%= link_to chunk.title, @book.closed? ? book_chunk_path(@book, chunk) : edit_book_chunk_path(@book, chunk) %></td>
            <td><%= chunk.section %></td>
            <td><%= chunk.username %></td>
            <td><%= chunk.versions.last.id unless chunk.versions == nil %></td>
            <% unless @book.closed? %>
                <td><%= button_to I18n.t('views.destroy'), book_chunk_path(@book, chunk), method: :delete, data: {confirm: I18n.t('views.are_you_sure')} %> </td>
                <td><%= button_to "Versions", chunk_version_path(@book, chunk), method: :get %> </td>
            <% end %>
          </tr>
      <% end %>
    </table>
<% else %>
    <p><%= I18n.t('views.chunk.index.empty') %></p>
<% end %>

<br/>

<% unless @book.closed? %>
    <%= button_to I18n.t('views.chunk.index.new'), new_book_chunk_path(@book), method: :get %>
<% end %>

<br/><br/>

<%= button_to I18n.t('views.back'), books_path, method: :get %>

app/views/books/show_advanced_searchform.js.erb
$("#advancedsearch").css('font-weight','Bold');
$("#simplesearch").removeAttr('style');
$("#searchform").html("<%= escape_javascript render(:partial => 'booksearches/form_extended') %>");

app/views/books/show_simple_searchform.js.erb
$("#simplesearch").css('font-weight', 'bold');
$("#advancedsearch").removeAttr('style');
$("#searchform").html("<%= escape_javascript render(:partial => 'booksearches/form_simple') %>");