config/routes.rb
BookWriter::Application.routes.draw do

  resources :booksearches

  get "conversations/index"

  mount Ckeditor::Engine => '/ckeditor'

  root :to => 'books#index'

  devise_for :users, :controllers => {:registrations => "registrations"} # route to custom controller for recaptcha verification

  resources :books do
    get 'print', :on => :member
    post 'close', :on => :member
    get 'new_edition', :on => :member
    resources :chunks, :except => [:index]
  end

  get 'show_simple_searchform' => 'books#show_simple_searchform' # for javascript
  get 'show_advanced_searchform' => 'books#show_advanced_searchform' # for javascript

  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
    end
  end
  get 'chunk_version/:book_id/:id' => 'chunks#version', :as => :chunk_version

  get 'conversations/:id' => "conversations#show", :as => :mailboxer_conversation, :constraints => {:id => /\d+/ } # generates  mailboxer_conversation_path
  post '/conversations/:id/reply' => "conversations#reply", :as => :reply_mailboxer_conversation # generates  reply_mailboxer_conversation_path

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
  <title>BookWriter</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="layout_container">

  <div id="top">

    <% if user_signed_in? %>
        <%= link_to I18n.t('views.layout.home'), books_path %> |
        <%= link_to image_tag('message.png'), conversations_path, :class => 'topclass' %> |
        <%= "#{I18n.t('views.layout.account')}: #{current_user.username}" %> |
        <%= link_to I18n.t('views.layout.my_account'), edit_user_registration_path %> |
        <%= link_to I18n.t('views.layout.logout'), destroy_user_session_path, method: :delete %>
    <% end %>

  </div>

  <div id="left">
    <%= yield :left %>
  </div>

  <div id="content">

    <% if flash[:notice] %>
        <p id="notice"><%= flash[:notice] %></p>
    <% end %>
    <% if flash[:error] %>
        <p id="error"><%= flash[:error] %></p>
    <% end %>

    <%= yield %>

  </div>

</div>

</body>
</html>

app/views/layouts/books_and_chunks.html.erb
<% content_for :left do %>
    <%= render partial: 'shared/books_tree', :locals => {:books => user_books} %>
<% end %>

<%= render template: 'layouts/application' %>

app/views/layouts/print.pdf.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />
  <title>BookWriter PDF-Export</title>
  <%= wicked_pdf_stylesheet_link_tag "print", :media => "all" %>
</head>
<body>

<div id="content">
  <%= yield %>
</div>

</body>
</html>